<?php
  namespace ADV\App;

  /**
   * Generated by PHPUnit_SkeletonGenerator on 2012-10-05 at 05:16:20.
   */
  class DisplayTest extends \PHPUnit_Framework_TestCase {
    /** @var Display **/
    protected $object;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
      $this->object = new Display;
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }
    /**
     * @covers ADV\App\Display::access_string
     * @todo   Implement testAccess_string().
     */
    public function testAccess_string() {
      $teststring = 'Tes&t String';
      $actual     = Display::access_string($teststring);
      $this->assertEquals(['Tes<span class="u">t</span> String', " accesskey='T'"], $actual);
      //test repeat use of same accesskey
      $actual = Display::access_string($teststring);
      $this->assertEquals(['Test String', ''], $actual);
      $actual = Display::access_string($teststring, true);
      $this->assertEquals('Test String', $actual);
    }
    /**
     * @covers ADV\App\Display::heading
     * @todo   Implement testHeading().
     */
    public function testHeading() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
    /**
     * @covers ADV\App\Display::is_voided
     * @todo   Implement testIs_voided().
     */
    public function testIs_voided() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
    /**
     * @covers ADV\App\Display::menu_link
     * @todo   Implement testMenu_link().
     */
    public function testMenu_link() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
    /**
     * @covers ADV\App\Display::menu_button
     * @todo   Implement testMenu_button().
     */
    public function testMenu_button() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
    /**
     * @covers ADV\App\Display::meta_forward
     * @todo   Implement testMeta_forward().
     */
    public function testMeta_forward() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
    /**
     * @covers ADV\App\Display::note
     * @todo   Implement testNote().
     */
    public function testNote() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
    /**
     * @covers ADV\App\Display::link_params
     * @todo   Implement testLink_no_params().
     */
    public function testLink_no_params() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
    /**
     * @covers ADV\App\Display::link_params_td
     * @todo   Implement testLink_no_params_td().
     */
    public function testLink_no_params_td() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
    /**
     * @covers ADV\App\Display::link_params
     * @todo   Implement testLink_params().
     */
    public function testLink_params() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
a    }
    /**
     * @covers ADV\App\Display::submenu_option
     * @todo   Implement testSubmenu_option().
     */
    public function testSubmenu_option() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
    /**
     * @covers ADV\App\Display::submenu_print
     * @todo   Implement testSubmenu_print().
     */
    public function testSubmenu_print() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
    /**
     * @covers ADV\App\Display::viewer_link
     * @todo   Implement testViewer_link().
     */
    public function testViewer_link() {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
        'This test has not been implemented yet.'
      );
    }
  }
